version: '3.7'

services:

  t4_craft_sampleapp_mysql:
    image: mysql:5.6.50
    volumes:
      - ./db/craft_sample_app.sql:/docker-entrypoint-initdb.d/craft_sample_app.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz1qaz

  t4_craft_sampleapp_php:
    # see
    image: 24hoursmedia/pfpm73rutor:1.1.1
    volumes:
      - .:/var/www/html:delegated
    environment:
      PRIMARY_SITE_URL: http://localhost:8097
      DB_SERVER: t4_craft_sampleapp_mysql
      DB_USER: root
      DB_PASSWORD: 1qaz1qaz

  t4_craft_sampleapp_nginx:
    # see https://github.com/24HOURSMEDIA/docker-nginx4devs
    image: 24hoursmedia/nginx4devs:1.2.1
    environment:
      config_handle: craft3
      # config specific settings
      phpfpm_host: t4_craft_sampleapp_php
    ports:
      - "8097:80"
    depends_on:
      - t4_craft_sampleapp_php
    volumes:
      - ./web:/var/www/html/web:cached,ro



