field: afadcb1e-234b-4c7e-b927-9bfaf9c724c8
fieldLayouts:
  6027090c-2fa1-4f05-a334-cabdad3b1f18:
    tabs:
      -
        elements:
          -
            fieldUid: 7d0babff-760a-4351-afb1-3e4844e53295
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 70a0d9df-1da6-4ebd-a54a-8ded2d2705f7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  70a0d9df-1da6-4ebd-a54a-8ded2d2705f7:
    contentColumnType: string
    fieldGroup: null
    handle: entry
    instructions: ''
    name: Entry
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  7d0babff-760a-4351-afb1-3e4844e53295:
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: ''
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: menuItem
name: 'Menu item'
sortOrder: 1
