contentColumnType: boolean
fieldGroup: a7447568-5403-428a-888e-5fe6c45e7ae4
handle: showComments
instructions: 'Shows comments left for this article. Ignored if ''Enable commenting'' is on.'
name: 'Show comments'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
